version: '3.8'
services:
  # app:
  #   build: .
  #   command: npm run start:dev
  #   volumes:
  #     - ./:/app
  #     - /app/node_modules
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - postgres
  #     - pgadmin
  postgres:
    image: 'postgres:16.3-alpine'
    environment:
      - POSTGRES_USER=application
      - POSTGRES_PASSWORD=application
    ports:
      - '5432:5432'
    volumes:
      - ./data:/var/lib/postgresql/data
  pgadmin:
    image: 'dpage/pgadmin4'
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
